import type { Metadata } from "next";
import Link from "next/link";
import { EditorialShell, EditorialSection as Section, EditorialFAQ, ProductProof } from "@/components/editorial/Editorial";
import s from "@/components/editorial/editorial.module.css";
const url = "https://toumaiai.com/intelligence-artificielle-tchad/";
const title = "Intelligence artificielle au Tchad — Toumaï AI";
const description = "Découvrez Toumaï AI, conçu à N’Djamena : rédaction, recherche web, documents et usages multilingues. Une IA tournée vers les réalités du Tchad.";
export const metadata: Metadata = {
 title:{absolute:title}, description, alternates:{canonical:url,languages:{}},
 openGraph:{title,description,url,type:"website",locale:"fr_FR",images:[{url:"/og-image.png",alt:"Toumaï AI"}]},
 twitter:{card:"summary_large_image",title,description,images:["/og-image.png"]},
};
const faq = [
 {q:"Existe-t-il une intelligence artificielle tchadienne ?",r:"Toumaï AI est un assistant conçu à N’Djamena par Faycal Habib Ahmat. Il réunit conversation et outils de travail sur le web. Son ancrage tchadien ne signifie pas que tous ses modèles ou serveurs sont développés ou hébergés au Tchad."},
 {q:"Toumaï AI est-il gratuit ?",r:"Une offre gratuite permet de commencer sans carte bancaire, avec des limites d’utilisation. Les capacités et quotas varient selon la formule. Consultez les offres à jour sur la page d’accueil ; les paiements payants restent soumis à leur activation."},
 {q:"Toumaï comprend-il l’arabe tchadien ?",r:"Vous pouvez essayer une demande en arabe tchadien en précisant les expressions locales. La qualité dépend du modèle et de la formulation : faites relire les traductions importantes par un locuteur. Nous ne présentons pas de score de maîtrise ni de corpus d’entraînement non documenté."},
 {q:"Est-il disponible sur Android ?",r:"Vous pouvez ouvrir toumaiai.com dans le navigateur de votre téléphone Android, sans installation. Cette page ne présente pas de lien vers une application native dont la disponibilité en boutique n’a pas été vérifiée."},
 {q:"Peut-il rechercher sur le web et analyser des documents ?",r:"Le produit propose la recherche web avec sources et l’analyse de fichiers, selon les outils et quotas disponibles sur votre compte. Vérifiez les sources originales et relisez les chiffres ou citations extraits d’un document."},
 {q:"Peut-il utiliser WhatsApp ?",r:"Un parcours de connexion WhatsApp existe dans Toumaï AI. Il nécessite de relier votre compte et de vérifier les autorisations. Les actions disponibles dépendent de l’état du connecteur ; consultez la page WhatsApp avant de commencer."},
 {q:"Faut-il une connexion rapide ?",r:"Une connexion reste nécessaire pour obtenir de nouvelles réponses. Certaines données déjà chargées sont conservées en cache ; le mode vocal mesure la qualité de liaison avec le serveur. Cela ne garantit ni fonctionnement hors ligne ni délai fixe."},
 {q:"Où sont traitées mes données ?",r:"Le service peut faire intervenir des hébergeurs et des fournisseurs de modèles tiers. Un produit conçu au Tchad n’implique pas un traitement exclusivement au Tchad. Consultez la politique de confidentialité avant d’envoyer des informations sensibles."},
 {q:"Quelle différence avec ChatGPT au Tchad ?",r:"Toumaï AI met l’accent sur les usages tchadiens, le multilingue, le mobile et les outils réunis dans une même interface. Le choix dépend de votre besoin, de la qualité des réponses et des fonctionnalités disponibles, sans affirmation de supériorité générale sur ChatGPT."},
];
const schema = {"@context":"https://schema.org","@graph":[
 {"@type":"WebPage","@id":url,url,name:title,description,inLanguage:"fr",about:{"@id":"https://toumaiai.com/#organisation"}},
 {"@type":"BreadcrumbList",itemListElement:[{"@type":"ListItem",position:1,name:"Accueil",item:"https://toumaiai.com/"},{"@type":"ListItem",position:2,name:"IA au Tchad",item:url}]},
 {"@type":"FAQPage",mainEntity:faq.map(({q,r})=>({"@type":"Question",name:q,acceptedAnswer:{"@type":"Answer",text:r}}))}
]};
export default function ChadPage() {
 return <EditorialShell>
 <script type="application/ld+json" dangerouslySetInnerHTML={{__html:JSON.stringify(schema).replace(/</g,"\\u003c")}}/>
 <nav aria-label="Fil d’Ariane" className={s.breadcrumb}><Link href="/">Accueil</Link> / IA au Tchad</nav>
 <section className={s.hero} aria-labelledby="page-title"><div><p className={s.eyebrow}>CONÇU À N’DJAMENA · OUVERT SUR LE MONDE</p><h1 id="page-title">L’intelligence artificielle <em>au Tchad.</em></h1><p className={s.lead}>Un espace pour chercher, comprendre et avancer. Toumaï AI est conçu à N’Djamena, avec les langues, les usages et les réalités du pays en point de départ.</p><div className={s.actions}><Link className={s.primary} href="/chat/">Ouvrir Toumaï ↗</Link><a href="#capacites">Voir ce qu’il peut faire ↓</a></div><p className={s.note}>Sur le web, depuis votre ordinateur ou votre téléphone.</p></div><ProductProof/></section>
 <div className={s.strip}><span>Une question, plusieurs outils.</span><a href="#capacites">Recherche & documents</a><a href="#langues">Français & arabe</a><a href="#reseau">Une attention au mobile</a></div>
 <Section id="contexte" label="01 / LE CONTEXTE" title="Pourquoi une IA conçue au Tchad ?"><div className={s.columns}><p className={s.lead}>À N’Djamena, Moundou ou Abéché, le besoin est concret : préparer un cours, relire un courrier, comprendre un document ou répondre à un client.</p><div><p>Le téléphone est souvent le point d’entrée. La connexion peut varier pendant une conversation. Et une demande ne s’exprime pas toujours dans une seule langue.</p><p>Toumaï AI réunit ces usages sans exiger de carte bancaire pour découvrir l’offre gratuite. Les moyens de paiement payants restent soumis à leur activation. L’ambition est locale dans son attention aux besoins, et internationale dans les usages.</p></div></div></Section>
 <Section id="capacites" label="02 / LE PRODUIT" title="De la question au travail accompli."><div className={s.capabilities}><article className={s.feature}><p className={s.eyebrow}>COMPRENDRE</p><h3>Chat, recherche & documents</h3><p>Posez une question, demandez une recherche sourcée ou travaillez à partir d’un fichier. Revenez au document et aux sources pour vérifier la réponse.</p><Link href="/chat/">Commencer une conversation ↗</Link></article><div className={s.rows}>{[["Créer","Rédaction, code, images : donnez un objectif, puis affinez le résultat. Testez le code et relisez les contenus avant usage."],["Échanger","Dictée et voix permettent d’alterner entre texte et oral, selon les capacités disponibles sur votre compte."],["Relier vos outils","WhatsApp, connecteurs et agents prolongent la conversation vers des actions. Une connexion et les autorisations adaptées sont nécessaires."]].map(([t,d])=><article key={t}><h3>{t}</h3><p>{d}</p></article>)}</div></div><p className={s.note}>Selon le modèle, la formule et l’état des connecteurs. <Link href="/models/">Explorer les modèles</Link> · <Link href="/whatsapp/">Comprendre WhatsApp</Link></p></Section>
 <Section id="langues" label="03 / LES LANGUES" title="Votre idée, dans vos mots."><div className={s.languages}><article><span>FR</span><h3>Français</h3><p>Rédiger un courrier, expliquer un cours, structurer une idée.</p><blockquote>« Aide-moi à rendre ce message plus clair. »</blockquote></article><article lang="ar" dir="rtl"><span>AR</span><h3>العربية</h3><p>اطلب شرحًا أو ملخصًا، وراجع التفاصيل المهمة.</p><blockquote>« ساعدني في صياغة هذه الرسالة بوضوح. »</blockquote></article><article><span>TD</span><h3>Arabe tchadien</h3><p>Précisez le contexte et les expressions locales. Les variantes et transcriptions peuvent demander des reformulations.</p><small>Pas de niveau de maîtrise chiffré sans évaluation publiée.</small></article></div><p className={s.note}>Exemples de demandes, pas résultats d’un benchmark. <Link href="/ar/" hrefLang="ar">Découvrir la présentation en arabe ↗</Link></p></Section>
 <Section id="reseau" label="04 / LA CONNECTIVITÉ" title="Pensé pour le réseau d’ici."><div className={s.network}><div><h3>Ce qui est chargé ne doit pas disparaître au premier ralentissement.</h3><p>Le cache conserve certaines données déjà consultées et les actualise en arrière-plan. Le mode vocal mesure la liaison vers le serveur pour signaler une connexion dégradée.</p><p>Une nouvelle réponse, un fichier à envoyer ou une recherche web nécessitent toujours le réseau. Les images et la voix peuvent être plus exigeantes que le texte.</p></div><ol><li><strong>Consulter</strong><span>Réutiliser les données mises en cache.</span></li><li><strong>Actualiser</strong><span>Récupérer les données récentes quand la connexion le permet.</span></li><li><strong>Rester informé</strong><span>Signaler la qualité de liaison en mode vocal.</span></li></ol></div></Section>
 <Section id="confiance" label="05 / LE CONTRÔLE" title="Vous gardez le contrôle."><div className={s.columns}><p className={s.lead}>Une réponse est un point de départ. Une action engage votre compte.</p><div><p>Relisez les réponses, vérifiez les sources et examinez les confirmations avant les actions sensibles des connecteurs, comme un envoi de message. Vérifiez le cadre d’utilisation avant de partager des données confidentielles.</p><div className={s.actions}><Link href="/privacy/">Confidentialité ↗</Link><Link href="/security/">Sécurité ↗</Link><Link href="/terms/">Conditions ↗</Link></div></div></div></Section>
 <Section id="origine" label="06 / L’ORIGINE" title="Un projet ancré à N’Djamena."><div className={s.columns}><p>Toumaï AI est développé par Faycal Habib Ahmat. Le projet porte une attention particulière aux usages au Tchad et à la place des langues dans l’intelligence artificielle en Afrique.</p><p>Le nom Toumaï renvoie à un symbole scientifique associé au Tchad. Découvrez <Link href="/a-propos/">l’histoire du projet</Link>, sans confondre cette identité avec une preuve de performance technique.</p></div></Section>
 <Section id="atelier" label="07 / UN EXERCICE CONCRET" title="Préparer un document, sans perdre le contexte."><div className={s.columns}><div><h3>Pour un étudiant ou un entrepreneur</h3><p>Partez d’un document que vous avez le droit de partager. Retirez les numéros de téléphone, identifiants et informations confidentielles qui ne sont pas nécessaires.</p><blockquote>« Résume ce document en cinq points. Sépare les faits des hypothèses. Signale les informations manquantes et propose trois questions à poser avant de décider. »</blockquote></div><div><h3>Ce qu’il faut contrôler</h3><p>Comparez les noms, montants et dates avec l’original. Si le document utilise des expressions locales, expliquez-les plutôt que de supposer que le modèle les connaît. Pour un texte destiné à être publié, demandez une relecture humaine.</p><p>Cette méthode est un exemple de travail, pas un résultat mesuré ni une garantie d’exactitude. <Link href="/assistant-ia/">Découvrir le parcours de l’assistant</Link> et <Link href="/models/">choisir un modèle selon la tâche</Link>.</p></div></div></Section>
 <EditorialFAQ items={faq}/>
 <section className={s.final}><p className={s.eyebrow}>À VOUS D’ESSAYER</p><h2>Commencez par une vraie question.</h2><p>Un cours à comprendre. Un texte à améliorer. Une idée à explorer.</p><Link className={s.primary} href="/chat/">Ouvrir Toumaï ↗</Link></section>
 </EditorialShell>;
}
