import type { Dict } from "./fr";

/**
 * Anglais.
 *
 * Ce n'est pas une traduction mot à mot : « Parlez comme chez vous » devient
 * « Speak the way you speak at home », parce que le calque « Speak like at
 * home » ne veut rien dire. Ce qui doit passer, c'est la promesse, pas la
 * syntaxe française.
 */
export const en: Dict = {
  nav: {
    capacites: "Capabilities",
    pourquoi: "Why Toumaï",
    modeles: "Models",
    connecteurs: "Connectors",
    login: "Sign in",
    register: "Sign up",
    logout: "Sign out",
    tryFree: "Try it free",
    tryShort: "Try it",
    openApp: "Open Toumaï AI",
    openShort: "Open",
    menuOpen: "Open menu",
    menuClose: "Close menu",
    menu: "Menu",
    skip: "Skip to content",
    appearance: "Appearance",
    language: "Language",
    ariaMain: "Main navigation",
  },

  hero: {
    badge: "Built in N'Djamena, made for the world",
    titleA: "Speak the way",
    titleEm: "you speak at home.",
    leadA: "Toumaï AI understands French, English and Arabic — including",
    leadStrong: "Chadian Arabic",
    leadB: ", the one spoken at the market, not the one in textbooks.",
    ctaPrimary: "Start for free",
    ctaSecondary: "See Toumaï AI at work",
    countRegistered: "sign-ups",
    countConversations: "conversations",
    trust: ["Free, no card required", "Web and WhatsApp, nothing to install", "Your data is never sold"],
    heroImgAlt: "",
  },

  console: {
    aria: "Toumaï AI demo: conversation, Chadian Arabic, image generation, voice mode and Browser Agent",
    live: "Live",
    paused: "Paused",
    pause: "Pause the demo",
    resume: "Resume the demo",
    scenesAria: "Demo scenes",
    sceneAria: (n, total, name) => `Scene ${n} of ${total}: ${name}`,
    tabs: {
      fr: "Conversation",
      shu: "Chadian Arabic",
      image: "Image",
      voice: "Voice",
      agent: "Browser Agent",
    },
    fr: {
      shotAlt:
        "Toumaï AI on a phone: “Write a message announcing my shop opening on Saturday in N'Djaména.” The answer drafts a full announcement — grand opening Saturday, Dembé market from 8 a.m., clothing, accessories and fabrics, launch prices all day.",
      ask: "Write a message announcing my shop opening this Saturday in N'Djamena.",
      thinking: "Sao 4 is writing…",
      answer:
        "Grand opening this Saturday! Come and see our shop at Dembé market from 9 a.m. — launch offers all day long.",
      chips: ["Shorter", "In Arabic", "WhatsApp version"],
    },
    shu: {
      ask: "How do you say “How are you today?” in Chadian Arabic?",
      thinking: "Looking it up in Chadian Arabic…",
      answer:
        "That's the everyday phrasing. Literary Arabic would say “كيف حالك اليوم؟” — correct, but nobody talks like that at the market in N'Djamena.",
      chips: ["Chadian Arabic", "Literary Arabic", "French"],
    },
    image: {
      ask: "Generate an image of a modern African entrepreneur in an elegant office.",
      thinking: "Ennedi is composing the image…",
      caption: "Image generated by Toumaï AI",
      chip: "Signature included",
      alt: "Toumaï AI on a phone: the request for an image of an African entrepreneur, and the rendered image just below, signed Toumaï AI",
    },
    voice: {
      ask: "Remind me what we agreed yesterday about the delivery.",
      engine: "KANEM FLASH · SPEAKS THE ANSWER",
      answer: "Delivery Friday morning, payment on handover. Shall I put that in writing?",
      chips: ["Interrupt any time", "Hands-free"],
    },
    agent: {
      ask: "Find Friday's flight times from N'Djamena to Abéché.",
      searching: "searching…",
      steps: [
        { label: "Opens the search engine", meta: "search" },
        { label: "Compares three result pages", meta: "reading" },
        { label: "Pulls out times and address", meta: "extraction" },
        { label: "Reports back — confirms nothing alone", meta: "report" },
      ],
      note: "Anything that commits you is put to you before it happens.",
    },
  },

  showcase: {
    eyebrow: "Toumaï AI at work",
    titleA: "Eight ways to",
    titleEm: "put it to work",
    titleB: ", one conversation.",
    lead: "No menus to learn. You type, you speak, you drop in a file — Toumaï AI takes it from there.",
    listAria: "Toumaï AI capabilities",
    pause: "Stop cycling through capabilities",
    resume: "Resume cycling through capabilities",
    pauseLabel: "Pause",
    resumeLabel: "Resume",
    caps: {
      multilingue: { label: "Multilingual chat", short: "Multilingual", line: "French, English, Arabic — in one conversation." },
      tchadien: { label: "Chadian Arabic", short: "Chadian Arabic", line: "Everyday speech, not textbook Arabic." },
      image: { label: "Image generation", short: "Images", line: "Describe the scene, Toumaï AI composes it." },
      document: { label: "Document analysis", short: "Documents", line: "A PDF goes in, the essentials come out." },
      code: { label: "Programming", short: "Code", line: "Write, explain, fix, run." },
      web: { label: "Browser Agent", short: "Agent", line: "One task handed over, carried out step by step." },
      voix: { label: "Voice mode", short: "Voice", line: "Speak, and it answers out loud." },
      connecteurs: { label: "Connectors", short: "Connectors", line: "WhatsApp, email, calendar — under your control." },
    },
    langues: {
      shotAlt:
        "Toumaï AI on a phone: “How do you say ‘I have no money’ in French, English, Arabic and Chadian Arabic?” The answer gives all four versions, each with its flag, then jokes that the budget is now multilingual.",
      title: "One conversation, several languages",
      note: "fr · ar · en",
      rows: [
        { hello: "Bonjour", lang: "Français", reply: "Comment puis-je vous aider aujourd'hui ?" },
        { hello: "مرحبا", lang: "العربية", reply: "كيف يمكنني مساعدتك اليوم؟" },
        { hello: "Hello", lang: "English", reply: "How can I help you today?" },
      ],
      foot: "Switch language mid-thread: the conversation carries on.",
    },
    tchadien: {
      title: "Arabic the way it's spoken here",
      note: "chadian · shuwa",
      msaLabel: "literary",
      rows: [
        { fr: "How are you?", shu: "إنت كيف؟", tr: "inta kēf ?", msa: "كيف حالك؟" },
        { fr: "I'm coming from the market", shu: "أنا جاي من السوق", tr: "ana jāy min as-sūg", msa: "أنا قادم من السوق" },
        { fr: "There's no problem", shu: "ما في مشكلة", tr: "mā fī mushkila", msa: "لا توجد مشكلة" },
      ],
      note2:
        "Toumaï AI is built on a corpus of Chadian Arabic collected in the field — not a translation from literary Arabic.",
    },
    image: {
      prompt: "“Generate an image of a modern African entrepreneur in an elegant office.”",
      promptLabel: "Your prompt",
      alt: "Toumaï AI on a phone: the request for an image of an African entrepreneur, and the rendered image just below",
      chips: ["Toumaï AI signature included", "Ennedi model", "Downloadable"],
    },
    document: {
      shotAlt:
        "Toumaï AI on a phone: a 2.8 MB, 24-page PDF “Rapport_financier_2024” is attached to an analysis request. The summary comes back in three numbered parts — overall results, main expenses, 2025 projections — with figures in CFA francs.",
      title: "A document goes in, the essentials come out",
      note: "pdf · docx · image",
      file: "contract.pdf",
      points: [
        "Term: 12 months, auto-renewing",
        "Notice period: 60 days",
        "Late penalty: 3% per month",
        "Watch out: clause 7.2, exclusivity",
      ],
      foot: "Then ask your questions about it: the answers stay tied to what the document actually says.",
    },
    code: {
      shotAlt:
        "Toumaï AI on a phone: “Write me a Python function that checks whether an email address is valid.” The answer shows syntax-highlighted code — an `re` import and an `email_valide` function — followed by a line explaining it returns True or False. Toumaï 5 model.",
      file: "average.py",
      lang: "Python",
      aria: "A Python function that averages a list of marks, followed by its output",
      outputLabel: "Run in the browser",
    },
    web: {
      shotAlt:
        "Toumaï AI on a phone: “Search the web for the most important tech news in Africa this week.” The answer lists five topics — internet satellite, startup growth, regional data centres, AI in education, Chad's digital push — each with a short summary.",
      title: "A task handed over to the web",
      note: "browser agent",
      searching: "searching",
      steps: [
        { label: "Frames the search", detail: "N'Djamena → Abéché, Friday" },
        { label: "Opens the results", detail: "3 sources compared" },
        { label: "Pulls out the answer", detail: "times, stops, listed fare" },
        { label: "Reports back", detail: "with the source links" },
      ],
      foot: "The agent asks you first before anything that commits you.",
    },
    voix: {
      shotAlt:
        "Toumaï AI voice mode on a phone: a glowing orb pulsing through the exchange, with microphone, call and speaker controls beneath it, and a text field to switch back to typing.",
      ask: "“Sum up yesterday's meeting for me.”",
      note: "End-of-sentence detection · spoken reply",
      answer: "Three decisions: delivery on Friday, payment on handover, and a check-in next Monday.",
      chips: ["Dictation", "Read aloud", "Interrupt any time"],
    },
    connecteurs: {
      shotAlt:
        "Toumaï AI on a phone: “Summarise Ahmat's voice message.” The answer — he confirms Friday's delivery and asks for an invoice in the co-op's name. Then “Reply that I agree”, and Toumaï AI asks for confirmation before sending, with two buttons: Send and Edit.",
      title: "Your tools, inside the conversation",
      note: "revocable",
      available: "Available",
      items: [
        { name: "WhatsApp", detail: "Read, summarise, reply — contact by contact." },
        { name: "Email", detail: "Sort, draft, find a thread." },
        { name: "Google Calendar", detail: "Check, create, move an appointment." },
      ],
      permsLabel: "Permissions — each one switches off on its own",
      perms: ["Read messages", "Send a message", "Summarise a chat", "Post a status"],
      foot: "Anything sensitive always asks you first.",
      manage: "Manage connectors",
    },
  },

  marquee: [
    { t: "Bonjour", s: "french" },
    { t: "مرحبا", s: "arabic", rtl: true },
    { t: "Hello", s: "english" },
    { t: "إنت كيف؟", s: "chadian arabic", rtl: true, hot: true },
    { t: "Comment ça va ?", s: "french" },
    { t: "ما في مشكلة", s: "chadian arabic", rtl: true, hot: true },
    { t: "How can I help?", s: "english" },
    { t: "كيف حالك؟", s: "literary arabic", rtl: true },
  ],

  why: {
    shotAlt:
      "Toumaï AI on a phone: “I have 150,000 CFA francs to start a small business in N'Djamena. What do you advise?” — the answer lays out three steps, from picking the service to splitting the budget.",
    eyebrow: "Why Toumaï AI",
    titleA: "An assistant is only useful if it truly",
    titleEm: "understands you.",
    lead:
      "The big models speak to the whole world. Few of them know what gets said at Dembé on a Saturday morning, or what “there's no problem” means when there is one.",
    r1: {
      title: "It knows the context here",
      body: "The towns, the markets, the paperwork, the turns of phrase. An answer that's right elsewhere can be useless in N'Djamena — Toumaï AI is built from that context, not in spite of it.",
    },
    r2: {
      title: "Three languages, yours among them",
      body: "French, English, Arabic — and Chadian Arabic, built from a corpus collected in the field.",
      rows: [
        { w: "Bonjour", l: "Français" },
        { w: "مرحبا", l: "العربية", rtl: true },
        { w: "إنت كيف؟", l: "Chadian Arabic", rtl: true, hot: true },
        { w: "Hello", l: "English" },
      ],
    },
    r3: {
      title: "It sees, reads, listens and speaks",
      body: "A photo, a PDF, a voice note, a question typed in a hurry: it all goes into the same conversation.",
      modes: ["See", "Read", "Listen", "Speak"],
    },
    r4: {
      title: "It works where you already work",
      body: "On the web, inside WhatsApp, and soon on Android. And it plugs into your inbox and your calendar — one capability at a time, revocable whenever you want.",
      chips: ["Web", "WhatsApp", "Email", "Google Calendar", "Browser Agent", "Android — soon"],
    },
    freeA: "Free.",
    freeEm: "No card required.",
    freeBody: "Chat, images, voice, agents and connectors: all of it open, with no subscription and no trial period.",
    privacyA: "Your conversations",
    privacyEm: "are not for sale.",
    privacyBody:
      "No data resale, no ads targeted from what you write. You delete your conversations whenever you like.",
    privacyLink: "Privacy policy",
    ctaLabel: "Try it now",
    ctaNote: "No account needed to start.",
  },

  everywhere: {
    eyebrow: "Wherever you are",
    titleA: "It comes to you.",
    titleEm: "Not the other way round.",
    web: {
      kicker: "On the web",
      title: "Open it, type. That's all.",
      body: "Nothing to install, nothing to set up. You can try it before you even create an account.",
      points: ["No install", "Try without an account", "History synced once you sign in"],
      cta: "Open Toumaï AI",
    },
    whatsapp: {
      kicker: "Inside WhatsApp",
      title: "One more contact, nothing new to learn.",
      body: "You write to it like anyone else — questions, voice notes, photos. It answers in the thread.",
      points: ["No extra app", "Voice notes understood", "Each capability switches off on its own"],
      cta: "See the connectors",
    },
    mobile: {
      kicker: "On Android",
      title: "Coming to your pocket.",
      body: "The Android app is in the works: it will pick up your history and let you reread past threads offline. It is not published yet.",
      points: ["In development", "History carried over", "Hands-free voice mode"],
      cta: "Use the web in the meantime",
      badge: "In the works",
    },
    devices: {
      web: "Toumaï AI open in a browser: a question in French, an answer starting in Chadian Arabic",
      whatsapp: "A WhatsApp thread with Toumaï AI, on a phone",
      mobile: "The Toumaï AI Android app: home screen, suggestions and voice mode",
      newChat: "+ New",
      composer: "Message Toumaï AI…",
      message: "Message",
      online: "online",
      translate: "Translate this into Chadian Arabic.",
      waAsk: "Sum up Ahmat's voice note for me.",
      waAnswer: "He confirms Friday's delivery and asks for an invoice in the co-op's name.",
      waAsk2: "Tell him that works.",
      waAnswer2: "Message ready. Shall I send it?",
      greeting: "Good evening.",
      greetingSub: "Where shall we start?",
      suggestions: ["Translate into Chadian Arabic", "Summarise a document", "Generate an image"],
    },
  },

  intelligence: {
    shotAlt:
      "Toumaï AI voice mode: a glowing orb pulsing through the exchange, with microphone, call and speaker controls beneath it.",
    eyebrow: "The intelligence behind Toumaï",
    titleA: "You type. Toumaï AI picks",
    titleEm: "the right engine.",
    lead: "A family of models, routed automatically. No settings, no menus — and you can always take over in the model picker.",
    defaultBadge: "Default",
    sao: {
      tag: "The everyday model",
      desc: "Conversation, writing, translation, code, summaries. Fast, and the default.",
      points: ["Streamed answers", "At home in French and Arabic", "Understands Chadian speech"],
    },
    toumai: {
      tag: "Reasoning — deep thinking",
      desc: "For anything that demands rigour: maths, planning, analysis, decisions.",
      points: ["Step-by-step reasoning", "Built for complex tasks", "Selectable in the chat"],
    },
    routerTitle: "Routing, live",
    routerFlow: "request → understanding → engine → result",
    yourRequest: "Your request",
    engines: {
      sao: "Code & everyday help",
      toumai: "Deep reasoning",
      ennedi: "Image generation",
      ouaddai: "Analysis & data",
      tibesti: "Development",
      kanem: "Voice conversations",
      chari: "Letters & reports",
    },
    requests: [
      { text: "Translate this into Chadian Arabic.", out: "Answered in the local speech" },
      { text: "Draw the dunes at dusk.", out: "Image generated, signed" },
      { text: "Summarise this 40-page contract.", out: "Key points pulled out" },
      { text: "Write a function that sorts a list.", out: "Code written, then run" },
      { text: "How long to pay this off at 3%?", out: "Step-by-step reasoning" },
      { text: "Read the answer out loud.", out: "Spoken answer" },
      { text: "Draft me a cover letter.", out: "Laid-out document" },
    ],
    foot: "Sao 4 and Toumaï 5 are chosen by hand in the model picker. The dedicated engines are called automatically, based on the request.",
    footLink: "All about the models",
    hubLabel: "Toumaï",
    hubSub: "ROUTER",
  },

  connectors: {
    eyebrow: "Connectors",
    titleA: "It doesn't just answer.",
    titleEm: "It acts.",
    lead: "Plug in your tools and ask in one sentence for what used to take five apps. Each capability switches on — and off — separately.",
    available: "Available",
    serviceOf: (owner) => `A ${owner} service`,
    items: [
      { name: "WhatsApp", does: ["Read and summarise a thread", "Draft and send a message", "Find a piece of information"] },
      { name: "Email", does: ["Sort the inbox", "Draft a reply", "Find an attachment"] },
      { name: "Google Calendar", does: ["Check the day", "Create an appointment", "Move a slot"] },
    ],
    safety:
      "Anything that sends, posts or changes something is always put to you first. You can restrict access to specific contacts, and withdraw a permission at any time.",
    manage: "Manage my connectors",
    trademark:
      "WhatsApp is a Meta trademark; Gmail and Google Calendar are Google's. Toumaï AI connects to them with your permission, with no partnership of any kind with these companies.",
  },

  faq: {
    eyebrow: "Frequently asked",
    titleA: "What people ask us",
    titleEm: "most often.",
    contactA: "Another question?",
    contactLink: "Write to us",
    items: [
      {
        q: "Is it really free?",
        a: "Yes, entirely. Chatting, generating images, voice mode, agents and connectors — all free, with no subscription and no card.",
      },
      {
        q: "Does it understand Chadian Arabic, or only standard Arabic?",
        a: "Both. Chadian Arabic is one of the project's first goals: Toumaï AI is built from a corpus collected in the field, so it understands and answers in everyday speech, alongside French and English.",
      },
      {
        q: "Is my data sold or used for advertising?",
        a: "No. Toumaï AI sells no data and runs no ads targeted from your conversations. The details are in the privacy policy.",
      },
      {
        q: "Does the WhatsApp connector read all my messages, all the time?",
        a: "No. Each capability (reading, sending, summarising…) switches off on its own, anything sensitive always asks you first, and you can restrict access to specific contacts or groups.",
      },
      {
        q: "Do I need an account to try it?",
        a: "No. You can open Toumaï AI and start chatting straight away. The account is what carries your history across devices and lets you plug in the connectors.",
      },
      {
        q: "Is the Android app available?",
        a: "Not yet. It is in the works and is not published on the Play Store. In the meantime, the web version works on a phone with nothing to install.",
      },
      {
        q: "Can I delete my conversations?",
        a: "Any time, straight from the interface — deleted at once, with no need to contact support.",
      },
    ],
  },

  partners: {
    eyebrow: "Partners & sponsors",
    titleA: "Let's build this AI",
    titleEm: "with you.",
    lead:
      "Toumaï AI is built in N'Djamena, for uses from here. Companies, institutions, schools, media: write to us about a partnership, a sponsorship or an integration.",
    kinds: ["Partnership", "Sponsorship", "Technical integration", "Research & data"],
    cta: "Write to us",
  },
  cta: {
    eyebrow: "One sentence away",
    titleA: "Say hello.",
    titleEm: "In your own language.",
    lead: "Free, no card, nothing to install. Open it and ask your first question.",
    primary: "Start for free",
    secondary: "Create an account",
    notes: ["Français · العربية · English", "Web and WhatsApp, nothing to install", "Conversations you can delete"],
  },

  footer: {
    blurb: "Named after the oldest known hominid, found in Chad. Intelligence, from the very beginning.",
    nav: "Footer",
    cols: {
      product: "Product",
      models: "Models",
      connectors: "Connectors",
      legal: "Account & legal",
    },
    links: {
      chat: "Chat",
      capabilities: "Capabilities",
      library: "Library",
      agent: "Browser Agent",
      whatsapp: "WhatsApp dashboard",
      modelsPage: "Sao 4 & Toumaï 5",
      routing: "Routing",
      aiChad: "AI in Chad",
      arabic: "النسخة العربية",
      overview: "Overview",
      manage: "Manage my connectors",
      settings: "Settings",
      register: "Create an account",
      login: "Sign in",
      terms: "Terms & policies",
      privacy: "Privacy policy",
      choices: "Privacy choices",
      deleteAccount: "Delete my account",
    },
    rights: (year) => `© ${year} Toumaï AI. Designed and built in N'Djamena, Chad.`,
  },
};
